name: lca-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - typer
  - mkdocs
  - mkdocs-material
  - snowflake-connector-python=2.7.2
  - ffmpeg
  - pydub
  - pip:
      - playwright
      - redshift-connector
      - pydantic[dotenv]
      - dominodatalab==1.0.6
      - dominodatalab-data==0.2.1