site_name: "LCA"
site_url: https://dominolowcode.github.io/
site_dir: site
edit_uri: ""
nav:
  - index.md
  - Install: install.md
  - Loading Data:
      - Loading Data from CSV: loading-data/csv.md
      - Loading Data from BigQuery: loading-data/bigquery.md
      - Loading Data from S3: loading-data/s3.md
      - Loading Data from Redshift: loading-data/redshift.md
      - Loading Data from Snowflake: loading-data/snowflake.md
      - Loading Data with SQL: loading-data/sql.md
  - Transformation:
      - Filtering Data: transform/filter.md
      - Grouping & Aggregating: transform/group-aggregate.md
      - Chaining Transformations: transform/chaining.md
  - Visualization:
      - Creating Plots: visualization/create-plot.md
  - Apps:
      - App creation: app/create.md
      - Examples:
          - Drug Classification App: app/example/drug-classification.md
          - Stocks App: app/example/stock.md
      - Deploy an App: app/deploy.md
      - Examples:
          - Embed App in Tableau: app/embed-tableau.md
      - Upload data to an App: app/upload.md
  - Code Snippets:
      - Using Snippets: snippets/snippets-using.md
      - Working with Snippets: snippets/snippets-working.md
      - Creating Snippets: snippets/snippets-creating.md
  - Domino Platform:
      - Settings: settings.md
      - Files: project/files.md
theme:
  name: material
  favicon: favicon.png
  logo: https://dominodatalab.github.io/api-docs/logo.png
  features:
    - content.tabs.link
    - navigation.expand
  custom_dir: overrides
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
repo_url: https://github.com/dominodatalab/low-code-jupyter-docs/
repo_name: low-code-jupyter-docs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown_include.include:
      base_path: docs
plugins:
  - redirects:
      redirect_maps:
        "getting-started.md": "index.md"
        "initialise.md": "install.md"
        "docs/install.md": "index.md"
        "data-from-csv-in-python.md": "loading-data/csv.md"
        "data-from-sql-in-python.md": "loading-data/sql.md"
        "connect-to-snowflake-in-python.md": "loading-data/snowflake.md"
        "connect-to-redshift-in-python.md": "loading-data/redshift.md"
        "connect-to-bigquery-in-python.md": "loading-data/bigquery.md"
        "connect-to-s3-in-python.md": "loading-data/s3.md"
  - exclude:
      regex:
        - ".*include.*"
